// <auto-generated />
namespace CMS.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addeddistricttouserstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeddistricttouserstable));
        
        string IMigrationMetadata.Id
        {
            get { return "201701251038420_added district to users table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
